from collections import OrderedDict

def substringFreq(string: str, n: int, printAll: bool) -> dict:
    """Returns a dictionary of frequencies of substring length n of a string, sorted by frequency.
    First removes all non-alphabetic characters and converts them to uppercase. """
    string = ''.join(filter(str.isalpha, string)).upper()

    freq = {}
    for i in range(len(string)-n+1):
        if string[i:i+n] in freq:
            freq[string[i:i+n]] += 1
        else:
            freq[string[i:i+n]] = 1
    freq = dict(OrderedDict(sorted(freq.items(), key=lambda i: i[1], reverse=True)))
    
    i=0
    for x in freq:
        if printAll:
            i += 1
            print(f"{i}\t{x}\t{freq[x]}")
        else:
            if freq[x] > 1:
                i += 1
                print(f"{i}\t{x}\t{freq[x]}")
    return freq

string = '''FSIKTSZDRCZEUGPFPOJWXRKCXVPVOQGSNESTECHYYEGKPCNOZCQMJTSFEVYSZEPXEDCCBGAGAHYHQCXRUSOKSTJCAUUSZURCEYTMJXDKWHZFEZRLETHHSSLMEQWZMCYCLJNOAZSPLHNGFXESIHSSXCVWOUQSTBLMEQWZMCYHNYGAERPPPROQPYOYIRNIXGBYOGWKSOZPREZOXRZKTRBFWREYPWYMAIKLXVPZGPTIOZPOVSYGAWKAXVPOYRNWEGEBOWYYISHIEBTQRYXIETXVPAOBQPAZLSCSOQNREYPOYRIYYPAJWOXCYGEMOREBOHNCZEFUVWEMUDGLAVSDFZGRVSJGVCFBJRBFWREYPWYZNXWQXFTPKGGMOKWHTAGRRHPNEHECHYYEGKAODTUPZIZJYFTBMYAITVPCDWULBJWHSIEMKYEWWMSKSWIFVWWTIFFDZGBROATSCJUJPEJUWIASXTBPYGRCEVGRVWIUYBEHUZNAETHPWCCLISHIEBTQGQULWYWDCSGBGSDGPTEVKCNVPNJFZAIFVRWZSGZIZFNJNOGOPJKLDYEZIGFFVPVWETKPPQGSFIEZXICBYMHXPNIGAFKYQSBZLSOIYRGSXKVSNCXBRHQVXCEVKLBVPNTCWSZFRINATHTCTMPGQXVSOTUPBRACISVOTBGLAJYGEPAPFXNKEQSSJIVPKSIHPFYYOSRKWSLZKTRPPNISGWJCAGALSIYRGJFSNKMBQCXARWPNIBZHOMAXDGXHSSLMEGAUJHSSKPHTPOSBLBJGGWKIIOYKGTRWYUYZOOTLVLEREHPZODRMJGXZLBZGFXDOWWYQOBRRPIEIDSJKNWOJIOEVLMYPKCIRMMZFRITZMBNHOMASBYSAPGVCPMAYEQNCXBVRCZSRYOKTVHATGSEVOQRVQVXWZBGJFSONVOYYZFRRQSFSCCLNRSLRIHZOHMHXKLXVPHURNPDAQOYDUNHPWZMCYCLRUIAGVHSOZRUEPZMAPOHMHXIOPZTCTNRSLRIOQHKPGLAKVIAHOMAEYGPRPFGUNWBUVAPRCFVGDZLSYTOJYIZCMHSKGRRVWTHPPQGKRADGXWDBUUXRKCRODHUZNPWQIIAKGPQTNKWGFFKZLXDKQORAGRUEPNEGYCZWRXYUQSZIZANYOKWHSSKKRVCKRQPCLQNQKYMFTGRYAHPNIFPWYYYWKLSZVZUPREXUYHECHYYEGKMGDOOBUIOGMRLHOKRADKRHSSXCJEOGJOCAKPAEIKHHZPGUUSSKRHQWYFVRCZSHSSXGIINZSUPHLGFLPUIOEHUZNKAZWOMWMYAHXKEIEWLSYJEYLPFHNCVWOAVDCWYCQXDGXHSSLGFLYGRHLZQYCTWXIBEZERUIBOWVTGZFRMJIEFYOZGBRKLEDCWTARWOCLCHOYAHVOKHTZFBGBPWZMBRHNCEYHKWCQHNCXMJMHCXOYYGLWTOMZILMELWBMBRFKJREOKHVPFLPBQPNIQFFYCGLAVVWYQKQFAWYQOCFERBFWNSKPJKPGLAXIWDCTCCVKSMGPHNYGLWYFSPBGEEIAJYDZBZFRCONSIWRTMGXARPOYMULRXDGXHSSVPVRYKWGTGGDVWDLVCXHNCZENXMORSCYFFKXROMCELNQAJWOXCYGEWWSSGTFMPRAETXCLJKPLLWTHGZAKYAHOZVCYUHMLFQZXVPFKYEIDGFWEGZFNXWSENPSBCECKTIVPORUNCOLISWGNSAKNEEBOBKTRVOGXWDTOCQEHRXVPTUMQVWZMCYGGPREHCEMDRKTBYNKHKTHNMHXPNIFPGZSAXERSBPRGWFEIUWWCOYQVKJKHHZRKJVZAXJCZRLMELEYJOEVKPVRPNITTSRBOYPZLSQCUBAIRKVQLAKRBFWGPGZOVNESWILSOGGKBWEXEBOOYIRHSNIFPHNCSSKJJCCVOKOYPYEAZGOPNHIOXHPRZFNXPNITZCJGFEHXIOOMKYGIJZSPLKGQIINEEBRFEYAHQTOBZKOLTPUHVSLYYFVWLXSATGKZLWWEMBRGULBJWLMGSGGKBWEXMAXSJGNXARCQZAVJNMJKHHZVOQZSPNIFTTNCPEHRIRLGULBJWLMGSHNCCVETGSDGCYFHEYEDACOLGIZHIQLIYCUINNYGMOTBUEOHVCVSTRUILXSATGKQUIYXMSOORMGEJJXCWRYYZSOOVHZFALGSPNIVTUNFVPHYYROSTJLZAXCVPOBWEEETGOXSJMJRSOXVLHKPEMXRIZTUNRAMJMXVPKGRRVKBIFQZUURHPUHFZKTRUIATXWCSBGYPWMIHSSVSQHHKXICBKBVRPUEZLYKRUEPOWBZKIYYPAJXCMORYXIPNIBEVKGFPWTHKSSXCFEIUWWCGNCYXAXMGNORJRHOGQCDWXGFPWTHHSOZQGLANMGECXWBJPUFOWOQCGLWZWGZITGDYAXMUSHODLSQBMGTHZMOEHGOSJCAANRBKIZEVKABSHGXAZGVFRVAUJHSSRYXIWIGCXDGLVIZHCPPOARVJQRZWPKYMSWWSSGTFOQYEJJ'''

substringFreq(string, 3, False)